/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/components/app.vue')['default']
    Chat: typeof import('./src/components/chat/chat.vue')['default']
    ChatAttachment: typeof import('./src/components/chat/chat-attachment.vue')['default']
    ChatAvatar: typeof import('./src/components/chat/chat-avatar.vue')['default']
    ChatCreateDialog: typeof import('./src/components/dialogs/chat-create-dialog.vue')['default']
    ChatHeader: typeof import('./src/components/chat/chat-header.vue')['default']
    ChatHeaderActions: typeof import('./src/components/chat/chat-header-actions.vue')['default']
    ChatInfoDialog: typeof import('./src/components/dialogs/chat-info-dialog.vue')['default']
    ChatList: typeof import('./src/components/chat/chat-list.vue')['default']
    ChatListItem: typeof import('./src/components/chat/chat-list-item.vue')['default']
    ChatMessage: typeof import('./src/components/messages/chat-message.vue')['default']
    ChatMessageActions: typeof import('./src/components/messages/chat-message-actions.vue')['default']
    ChatMessageAttachments: typeof import('./src/components/messages/chat-message-attachments.vue')['default']
    ChatMessages: typeof import('./src/components/messages/chat-messages.vue')['default']
    ChatMessageStatus: typeof import('./src/components/messages/chat-message-status.vue')['default']
    ChatRenameDialog: typeof import('./src/components/dialogs/chat-rename-dialog.vue')['default']
    Chats: typeof import('./src/components/chat/chats.vue')['default']
    ConfirmationDialog: typeof import('./src/components/dialogs/confirmation-dialog.vue')['default']
    ContactIcon: typeof import('./src/components/contacts/contact-icon.vue')['default']
    ContactList: typeof import('./src/components/contacts/contact-list.vue')['default']
    ContactListItem: typeof import('./src/components/contacts/contact-list-item.vue')['default']
    EmoticonsDialog: typeof import('./src/components/dialogs/emoticons-dialog.vue')['default']
    MessageDeleteDialog: typeof import('./src/components/dialogs/message-delete-dialog.vue')['default']
    MessageForwardDialog: typeof import('./src/components/dialogs/message-forward-dialog.vue')['default']
    PDialog: typeof import('./src/components/ui/p-dialog.vue')['default']
    PDropFiles: typeof import('./src/components/ui/p-drop-files.vue')['default']
    PInput: typeof import('./src/components/ui/p-input.vue')['default']
    PText: typeof import('./src/components/ui/p-text.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarLink: typeof import('@varlet/ui')['_LinkComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
  }
}
