/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/components/app.vue')['default']
    Chat: typeof import('./src/components/chat.vue')['default']
    ChatAvatar: typeof import('./src/components/chat-avatar.vue')['default']
    ChatCreateDialog: typeof import('./src/components/chat-create-dialog.vue')['default']
    ChatHeader: typeof import('./src/components/chat-header.vue')['default']
    ChatList: typeof import('./src/components/chat-list.vue')['default']
    ChatListItem: typeof import('./src/components/chat-list-item.vue')['default']
    ChatMessage: typeof import('./src/components/chat-message.vue')['default']
    ChatMessages: typeof import('./src/components/chat-messages.vue')['default']
    ChatMessageStatus: typeof import('./src/components/chat-message-status.vue')['default']
    Chats: typeof import('./src/components/chats.vue')['default']
    ContactIcon: typeof import('./src/components/contact-icon.vue')['default']
    ContactList: typeof import('./src/components/contact-list.vue')['default']
    PField: typeof import('./src/components/p-field.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarBadge: typeof import('@varlet/ui')['_BadgeComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarIndexAnchor: typeof import('@varlet/ui')['_IndexAnchorComponent']
    VarIndexBar: typeof import('@varlet/ui')['_IndexBarComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarSnackbar: typeof import('@varlet/ui')['_SnackbarComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
  }
}
